//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_BookAuthor
    {
        public int IdBook_BookAuthor { get; set; }
        public int IdBookAuthor { get; set; }
        public int IdBook { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual BookAuthor BookAuthor { get; set; }
    }
}
