//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManager.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Librarian_Session = new HashSet<Librarian_Session>();
        }
    
        public int IdSession { get; set; }
        public int IdReader { get; set; }
        public int IdBook { get; set; }
        public System.DateTime DateOfBegin { get; set; }
        public System.DateTime DateOfEnd { get; set; }
        public int IdLibrarian { get; set; }
    
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Librarian_Session> Librarian_Session { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
